"""
Django settings for graduationback project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'md%j*bx^*6nvis^29odn7zd)uh^k*ns9nzcrb6z^rqk57mniaa'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


APP_ID = 'wxf7ae0e9c9cccb92b'
APP_SECRET = '7d814e98ec55acb764ce1d225938a3e2'

# python 设置并获取环境变量
JWT_SECRET = 'sadfj;sdakf;'
JWT_AUD = os.environ.get('AUDIENCE', 'audience')
JWT_ISS = os.environ.get('ISS', 'iss')

ALLOWED_HOSTS = ['*']

# 七牛云配置

QINIU_ACCESS_KEY = 'P6bjJCH-jq4_kBhUsJc3zn1FXdi-XRwcOAAiDyUP'
QINIU_SECRET_KEY = 'QoWfm2RRgatI0vtgfFbEWeGVC48OkvzqEfWADySV'
QINIU_BUCKET_PUBLIC = 'testimage'
QINIU_CALLBACK_URL = ''
# QINIU_CALLBACK_BODY = 'name=$(fname)&hash=$(etag)&key=$(key)'
QINIU_DOMAIN_NAME = 'http://pp9lzpzq3.bkt.clouddn.com'
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Login.apps.LoginConfig',
    'rest_framework',
    'image.apps.ImageConfig',
    'product.apps.ProductConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'graduationback.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'graduationback.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }

    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',  # 数据库引擎
    #     'NAME': 'graduationback',  # 你要存储数据的库名，事先要创建之
    #     'USER': 'zhangfeiyu',  # 数据库用户名
    #     'PASSWORD': '863951vv',  # 密码
    #     'HOST': 'localhost',  # 主机
    #     'PORT': '3306',  # 数据库使用的端口
    # }
}
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    )
}
# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
IMAGE_FOLDER = 'images/'